name: Tests
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag tidyball .
    - name: Verifica el formato
      run: docker run tidyball make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run tidyball make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run tidyball make mutants
